sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gantakalyani/Docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gantakalyani/Docker-react npm run test
